### ISSUE TITLE
Poster Image for September 2022 Blog Post

### ISSUE THREAD

**Issue by kunalagra** [Mind-Benders/blog-content#3]
Hello Contributors,
We are looking for A good September 2022 Blog Cover/Poster Image. 
The image should have club's logo & should encompass the news in Sept'22.

This issue is for non-coders and requires Graphic Designing & etc. 

After being assigned the issue, please create the graphics and comment below with created image for suggestions/modifications & steps for PR.

**Comment by VaibhavAshta** [comment]
I would like to work on this. Please assign me this issue

**Comment by kunalagra** [comment]
Okay. Done. Please Upload your Idea for the Poster here for review.

**Comment by VaibhavAshta** [comment]
![This Month in AI](https://user-images.githubusercontent.com/88577836/193460530-cc62d90f-1a4c-4a45-bc44-a522a5351213.png)

**Comment by VaibhavAshta** [comment]
![This Month in AI September](https://user-images.githubusercontent.com/88577836/193460742-ec585b5f-6817-445c-8986-dbf63203f332.jpg)

**Comment by kunalagra** [comment]
Looks fantastic. Fork the Repo and add this image in posts/blog/September_2022 and make changes in Index.md as required
